sudo: false

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

install:
- export CXX="g++-5"

# Build steps
script:
  - cd project
  - make
