sudo: false

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

install:
- export CXX="g++-5"

# Build steps
script:
  - cd project
  - make

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    mkdir melkamar-pdp
    cp project/*.cpp project/*.h project/Makefile melkamar-pdp/
    rm -f melkamar-pdp.zip
    zip -r melkamar-pdp.zip melkamar-pdp/
    git add melkamar-pdp.zip
    git -c user.name='Martin Melka' -c user.email='melkamar@fit.cvut.cz' commit -m "Add zip."

    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
#    git push -f -q https://melkamar:$GITHUB_API_KEY@github.com/<me>/<myrepo>-gh-pages gh-pages &2>/dev/null
#    cd "$TRAVIS_BUILD_DIR"
    git push
  else
    echo "No github api key found"
  fi