sudo: false

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.4.0
    - g++-5.4.0
    - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5.4.0" CC="gcc-5.4.0"; fi

# Build steps
script:
  - cd project
  - make